extends: availity/browser
settings:
  import/core-modules:
    - react
    - config
rules:
  jsx-a11y/anchor-is-valid:
    - error
    - components:
      - Link
      specialLink:
      - to
      aspects:
      - noHref
      - invalidHref
      - preferButton
globals:
  graphql: false


