extends: availity/browser
settings:
  import/core-modules:
    - react # from gatsby
    - config # from gatsby
    - prop-types # from gatsby
    - react-helmet # from gatsby
rules:
  jsx-a11y/anchor-is-valid:
    - error
    - components:
        - Link
      specialLink:
        - to
      aspects:
        - noHref
        - invalidHref
        - preferButton
  react/forbid-prop-types: 0
  react/prop-types: 0
globals:
  graphql: false
