extends: availity/browser
rules:
  import/no-extraneous-dependencies: 0
  jsx-a11y/anchor-is-valid:
    - error
    - components:
      - Link
      specialLink:
      - to
      aspects:
      - noHref
      - invalidHref
      - preferButton


